PerpositionMutations_random_zygoticGenes.R ##### corrected RA tags of reads mapping only to zygotc genes
perPosition_numberOfMutations_randomReads.R #### corrected RA tags of reads mapping to cws > 5CPM + mitochondrial genes...
